//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrackingProject.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCompanies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCompanies()
        {
            this.TblCall = new HashSet<TblCall>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Authorized { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Sector { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCall> TblCall { get; set; }
    }
}
