//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrackingProject.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMessage
    {
        public int ID { get; set; }
        public Nullable<int> Sender { get; set; }
        public Nullable<int> Receiver { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TblCompanies TblCompanies { get; set; }
        public virtual TblCompanies TblCompanies1 { get; set; }
    }
}
