//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrackingProject.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTaskDetail
    {
        public int ID { get; set; }
        public Nullable<int> Task { get; set; }
        public string Statement { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
        public string Clock { get; set; }
    
        public virtual TblTask TblTask { get; set; }
    }
}
