//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTrackingProject.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTask()
        {
            this.TblTaskDetail = new HashSet<TblTaskDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> GiveTask { get; set; }
        public Nullable<int> GetTask { get; set; }
        public string Satement { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
    
        public virtual TblEmployee TblEmployee { get; set; }
        public virtual TblEmployee TblEmployee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTaskDetail> TblTaskDetail { get; set; }
    }
}
